# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'goodNewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for goodNewsApp
  
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'goodNewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'goodNewsAppUITests' do
    # Pods for testing
  end

end
